# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "CS130: Spring 2021"
subtitle: "Intro to the Web"
email: vanwars@northwestern.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/spring2021"
term_start_date: "2021-03-29"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
campuswire_url: https://campuswire.com/p/GB2462469

timezone: "America/Chicago"
# Build settings
markdown: kramdown
kramdown:
  auto_id_prefix: cs130_
theme: minima
plugins:
  - jekyll-feed
# exclude: [course-files]

collections:
  assignments:
    output: true
    sort_by: ordering
    permalink: /assignments/:name
  lectures:
    output: true
    sort_by: lecture_date
    permalink: /lectures/:name

collections_dir: pages

exclude:
  - "*drafts*"

sass:
  style: compact
  sass_dir: _sass

deadline_reminder: true


